Homework 2
irastruy/IrinaStruy_LevelUp pull request #3
Opened 2020-09-30 08:55 UTC by irastruy

2020-10-02 20:02 UTC, khda91 requested changes
Необходимо исправить комментарии

2020-10-02 20:02 UTC, khda91 commented on pom.xml
> +    <version>...</version>
Пропущен блок `build` с  `maven.compiler.plugin` который я просил вставить на занятии. 
Можно скопировать из проекта с занятий

2020-10-02 20:02 UTC, khda91 commented on pom.xml
> +    <version>...</version>
Почему эти параметры содержат значения `...`?

2020-10-02 20:02 UTC, khda91 commented on src/insteadOfLetter.txt
> +Дым табачный воздух выел.
Что-то мне подсказывает, что данная ветка была сделана от ветки `homework1` а не от `master`
Сделать **rebase** на `master` ветку

2020-10-02 20:02 UTC, khda91 commented on src/song.txt
> +
Что-то мне подсказывает, что данная ветка была сделана от ветки `homework1` а не от `master`
Сделать **rebase** на `master` ветку

2020-10-02 20:02 UTC, khda91 commented on src/homework_2/task_1/Calculator.java
> +    public static void main(String[] args) {
не выполнен пункт 4-6 из общих требований к домашней работе

2020-10-02 20:02 UTC, khda91 commented on src/homework_2/task_1/Calculator.java
> +        double num2 = sc3.nextDouble();
Можно написать общий метод, кторый будет принимать на вход строку какое число необходимо ввести и возвращать введённое число, которое можно будет записать в переменную

2020-10-02 20:02 UTC, khda91 commented on src/homework_2/task_1/Calculator.java
> +            Scanner sc4 = new Scanner(System.in);
`sc4` - не очень понятное имя для переменной

2020-10-02 20:02 UTC, khda91 commented on src/homework_2/task_1/Calculator.java
> +    }
Рекурсия конечно хороший вариант для вычисления числа Фиабоначи, но можно обойтись и без неё

2020-10-06 09:38 UTC, irastruy commented
Дмитрий, исправила замечания, отбранечевала ветку от мастера (была отбранчевана от непонятного комита), сделала новый пуш

2020-10-06 17:16 UTC, khda91 approved these changes
Домашняя работа принята. Можно мёржить в мастер

2020-10-08 10:53 UTC, merged